# Generated by Django 5.2.17 on 2026-08-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('issuer', models.CharField(blank=True, max_length=150)),
                ('credential_id', models.CharField(blank=True, max_length=150)),
                ('issue_date', models.CharField(max_length=50)),
                ('credential_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='cerificate/')),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('board_or_note', models.CharField(blank=True, max_length=200)),
                ('period', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Ritesh Kumar Das', max_length=150)),
                ('tagline', models.CharField(default='Django Backend Developer | Python', help_text='Short title shown under your name in the hero section.', max_length=200)),
                ('summary', models.TextField(help_text='Professional summary shown in the About section.')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('location', models.CharField(blank=True, default='India', max_length=100)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('extra_link_label', models.CharField(blank=True, help_text="Optional label for a third link, e.g. 'LeetCode'.", max_length=50)),
                ('extra_link_url', models.URLField(blank=True)),
                ('extracurricular', models.TextField(blank=True, help_text='E.g. cricket / sports / society achievements shown on the About section.')),
                ('is_open_to_work', models.BooleanField(default=True, help_text="Shows an 'open to work' badge in the hero.")),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('resume_file', models.FileField(blank=True, help_text='Upload a PDF so visitors can download your latest resume.', null=True, upload_to='resume/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('short_description', models.CharField(help_text='One or two sentences shown on the project card.', max_length=300)),
                ('detailed_description', models.TextField(blank=True)),
                ('tech_stack', models.JSONField(blank=True, default=list, help_text='List of technology tags, e.g. ["Django", "PostgreSQL", "Redis"].')),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('languages', 'Languages'), ('api_auth', 'APIs & Auth'), ('databases', 'Databases'), ('frontend', 'Frontend'), ('tools', 'Tools'), ('cs_fundamentals', 'CS Fundamentals'), ('soft_skills', 'Soft Skills')], default='backend', max_length=20)),
                ('icon', models.CharField(blank=True, help_text="Optional react-icons name, e.g. 'SiDjango', 'SiPostgresql', 'FaPython'.", max_length=50)),
                ('proficiency', models.PositiveSmallIntegerField(blank=True, help_text='Optional 0-100 self-rating.', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
