# Generated by Django 5.2.17 on 2026-08-24 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_remove_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='resume_file',
        ),
    ]
