# Generated by Django 5.2.17 on 2026-08-24 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_remove_profile_resume_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='certificate_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
