# Generated by Django 5.2.17 on 2026-08-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_remove_certification_certificate_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('backend', 'Backend'), ('languages', 'Languages'), ('api_auth', 'APIs & Auth'), ('databases', 'Databases'), ('frontend', 'Frontend'), ('tools', 'Tools'), ('cs_fundamentals', 'CS Fundamentals'), ('soft_skills', 'Soft Skills'), ('ml', 'ML'), ('algorithms', 'Algorithms'), ('dl', 'Dl'), ('model', 'Model')], default='backend', max_length=20),
        ),
    ]
